books_cbv/urls.py
from django.conf.urls import patterns, url

from books_cbv import views

urlpatterns = patterns('',
  url(r'^$', views.BookList.as_view(), name='book_list'),
  url(r'^new$', views.BookCreate.as_view(), name='book_new'),
  url(r'^edit/(?P<pk>\d+)$', views.BookUpdate.as_view(), name='book_edit'),
  url(r'^delete/(?P<pk>\d+)$', views.BookDelete.as_view(), name='book_delete'),
)

inventories/urls.py
from django.conf.urls import patterns, url, include
from .views import Registrarse
from inventories import views

urlpatterns = patterns('',
    url(r'^$', 'django.contrib.auth.views.login', {'template_name':'index_login.html'}, name='login'),
    url(r'^cerrar/$', 'django.contrib.auth.views.logout_then_login', name='logout'),
    url(r'^registrarse/$', Registrarse.as_view(), name='registrarse'),
    url(r'^books_cbv/' , include('books_cbv.urls', namespace='books_cbv')),

)

sw/urls.py
from django.conf.urls import patterns, include, url

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'sw.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
    
)

books_cbv/models.py
from django.db import models
from django.core.urlresolvers import reverse


class Book(models.Model):
    name = models.CharField(max_length=200)
    pages = models.IntegerField()

    def __unicode__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('books_cbv:book_edit', kwargs={'pk': self.pk})

customers/models.py
from django.db import models
from tenant_schemas.models import TenantMixin


class Client(TenantMixin):
    name = models.CharField(max_length=100)
    description = models.TextField(max_length=200)
    created_on = models.DateField(auto_now_add=True)

inventories/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class Inventory(models.Model):
    resume = models.CharField(max_length=200)
    date = models.DateTimeField('date')

    # def __unicode__(self):  # Python 3: def __str__(self):
    #     return self.resume
    
    def __init__(self, *args, **kwargs):
        super(Inventory, self).__init__(*args, **kwargs)


class Perfiles(models.Model):
	usuario = models.OneToOneField(User)
	telefono = models.IntegerField()

	def __unicode__(self):
		return self.usuario.username

customers/forms.py
from django import forms


class GenerateUsersForm(forms.Form):
    pass

inventories/forms.py
from django import forms
from django.core.exceptions import ValidationError

from django.contrib.auth.forms import UserCreationForm

from inventories.models import Inventory


class InventoryForm(forms.ModelForm):

    # confirm_email = forms.EmailField(
    #     label="Confirm email",
    #     required=True,
    # )

    class Meta:
        model = Inventory
        fields = ('resume', 'date')

    def __init__(self, *args, **kwargs):
        super(forms.ModelForm, self).__init__(*args, **kwargs)


class UserForm(UserCreationForm):
	pass

books_cbv/views.py
from django.http import HttpResponse
from django.views.generic import TemplateView,ListView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.core.urlresolvers import reverse_lazy

from books_cbv.models import Book

class BookList(ListView):
    model = Book

class BookCreate(CreateView):
    model = Book
    success_url = reverse_lazy('books_cbv:book_list')

class BookUpdate(UpdateView):
    model = Book
    success_url = reverse_lazy('books_cbv:book_list')

class BookDelete(DeleteView):
    model = Book
    success_url = reverse_lazy('books_cbv:book_list')

customers/views.py
from django.contrib.auth.models import User
from django.db.utils import DatabaseError
from django.views.generic import FormView
from customers.forms import GenerateUsersForm
from customers.models import Client
from random import choice


class TenantView(FormView):
    form_class = GenerateUsersForm
    template_name = "index_tenant.html"
    success_url = "/"

    def get_context_data(self, **kwargs):
        context = super(TenantView, self).get_context_data(**kwargs)
        context['tenants_list'] = Client.objects.all()
        context['users'] = User.objects.all()
        return context

    def form_valid(self, form):
        User.objects.all().delete()  # clean current users

        # generate five random users
        USERS_TO_GENERATE = 5
        first_names = ["Aiden", "Jackson", "Ethan", "Liam", "Mason", "Noah",
                       "Lucas", "Jacob", "Jayden", "Jack", "Sophia", "Emma",
                       "Olivia", "Isabella", "Ava", "Lily", "Zoe", "Chloe",
                       "Mia", "Madison"]
        last_names = ["Smith", "Brown", "Lee	", "Wilson", "Martin", "Patel",
                      "Taylor", "Wong", "Campbell", "Williams"]

        while User.objects.count() != USERS_TO_GENERATE:
            first_name = choice(first_names)
            last_name = choice(last_names)
            try:
                user = User(username=(first_name+last_name).lower(),
                            email="%s@%s.com" % (first_name, last_name),
                            first_name=first_name,
                            last_name=last_name)
                user.save()
            except DatabaseError:
                pass

        return super(TenantView, self).form_valid(form)

inventories/views.py
# Create your views here.
from django.http import HttpResponse
from django.views.generic import CreateView, ListView, UpdateView, DeleteView, TemplateView, FormView
from django.shortcuts import get_object_or_404, render
from django.http import HttpResponseRedirect
from django.core.urlresolvers import reverse
from django.views import generic
from django.core.urlresolvers import reverse_lazy
#from .models import Inventory, Perfiles
from .forms import UserForm

import forms

class Registrarse(FormView):
	template_name = 'registrarse.html'
	form_class = UserForm
	success_url = reverse_lazy('registrarse')

	def form_valid(self, form):
		user = form.save()
		user.save()
		return HttpResponseRedirect(reverse_lazy('books_cbv'))

sw/views.py
from django.conf import settings
from django.db import utils
from django.views.generic import TemplateView
from tenant_schemas.utils import remove_www_and_dev
from customers.models import Client


class HomeView(TemplateView):
    template_name = "index_public.html"

    def get_context_data(self, **kwargs):
        context = super(HomeView, self).get_context_data(**kwargs)

        hostname_without_port = remove_www_and_dev(self.request.get_host().split(':')[0])
        try:
            Client.objects.get(schema_name='public')
        except utils.DatabaseError:
            context['need_sync'] = True
            context['shared_apps'] = settings.SHARED_APPS
            context['tenants_list'] = []
            return context
        except Client.DoesNotExist:
            context['no_public_tenant'] = True
            context['hostname'] = hostname_without_port

        if Client.objects.count() == 1:
            context['only_public_tenant'] = True

        context['tenants_list'] = Client.objects.all()
        return context

books_cbv/templates/books_cbv/book_confirm_delete.html
<form method="post">{% csrf_token %}
    Are you sure you want to delete "{{ object }}" ?
    <input type="submit" value="Submit" />
</form>

books_cbv/templates/books_cbv/book_form.html
<form method="post">{% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Submit" />
</form>

books_cbv/templates/books_cbv/book_list.html
<h1>Books CBV</h1>
<ul>
    {% for book in object_list %}
    <li>{{ book.name }}  :  
    <a href="{% url "books_cbv:book_edit" book.id %}">Edit</a>
    <a href="{% url "books_cbv:book_delete" book.id %}">Delete</a>
    </li>
    {% endfor %}
</ul>

<a href="{% url "books_cbv:book_new" %}">New</a>

inventories/templates/edit_inventory.html
{% block content %}


<h1>Add Contact</h1>


<form action="{{ action }}" method="POST">
  {% csrf_token %}
  {% if form.non_field_errors %}
    <ul>
      {% for error in form.non_field_errors %}
        <li>{{ error }}</li>
      {% endfor %}
    </ul>
  {% endif %}
  {% for field in form %}
  <div id="{{ field.resume }}_container">
    {{ field.help_text }}
    <div>
      {{ field.label_tag }} {{ field }}
    </div>
    <div id="{{ field.date }}_errors">
      {{ field.errors }}
    </div>
  </div>
  {% endfor %}

  <input id="save_contact" type="submit" value="Save" />
</form>

{% endblock %}

inventories/templates/index_login.html
 {% if user.is_authenticated %}
                      Bienvenidooo {{user.username|capfirst}}
                      <a href="/cerrar/">Salir</a>
                    {% else %}
                    <form class="form-horizontal alinear" method="POST">{% csrf_token %}
                      <div class="control-group">
                        <label class="control-label" for="inputEmail" >Usuario</label>
                        <div class="controls">
                          <input name="username" type="text" id="inputEmail" placeholder="Usuario">
                        </div>
                      </div>

                      <div class="control-group">
                        <label class="control-label" for="inputPassword">Contraseña</label>
                        <div class="controls">
                          <input name="password" type="password" id="inputPassword" placeholder="Contraseña">
                        </div>
                      </div>

                      <div class="control-group">
                        <div class="controls">
                          <label class="checkbox">
                          <input type="checkbox">Recordar</label>
                          <button type="submit" class="btn btn-info">Ingresar</button>
                          <a href="/registrarse/" class="reg">Registrarse</a>
                        </div>
                      </div>
                    </form>
                    {% endif %}  

inventories/templates/inventories/edit_inventory.html
{% block content %}


<h1>Add Contact</h1>

{{ form.resume }}
{{ form.date }}
<form action="{{ action }}" method="POST">
  {% csrf_token %}
  {% if form.non_field_errors %}
    <ul>
      {% for error in form.non_field_errors %}
        <li>{{ error }}</li>
      {% endfor %}
    </ul>
  {% endif %}
  {% for field in form %}
  <div id="{{ field.resume }}_container">
    {{ fi
eld.help_text }}
    <div>
      {{ field.label_tag }} {{ field }}
    </div>
    <div id="{{ field.date }}_errors">
      {{ field.errors }}
    </div>
  </div>
  {% endfor %}

  <input id="save_contact" type="submit" value="Save" />
</form>

{% endblock %}

inventories/templates/inventories/index.html
{{ form.resume }}

inventories/templates/registrarse.html
<form method="POST">{% csrf_token %}
		{{form.as_p}}
		<input type="submit" value="Registrarse">
</form>

templates/base.html
<!DOCTYPE html>
<html lang="en"><head>
  <meta http-equiv="content-type" content="text/html; charset=utf-8">
  <title>{% block title %}{% endblock %}</title>
  <style type="text/css">
    html * { padding:0; margin:0; }
    body * { padding:10px 20px; }
    body * * { padding:0; }
    body { font:small sans-serif; }
    body>div { border-bottom:1px solid #ddd; }
    h1 { font-weight:normal; }
    h2 { margin-bottom:.8em; }
    h2 span { font-size:80%; color:#666; font-weight:normal; }
    h3 { margin:1em 0 .5em 0; }
    h4 { margin:0 0 .5em 0; font-weight: normal; }
    table { border:1px solid #ccc; border-collapse: collapse; width:100%; background:white; }
    tbody td, tbody th { vertical-align:top; padding:2px 3px; }
    thead th { padding:1px 6px 1px 3px; background:#fefefe; text-align:left; font-weight:normal; font-size:11px; border:1px solid #ddd; }
    tbody th { width:12em; text-align:right; color:#666; padding-right:.5em; }
    ul { margin-left: 2em; margin-top: 1em; }
    pre { background: white; padding: 10px; margin: 15px; border-left: 3px solid #006600; }
    #summary { background: #EFFFE0; }
    #summary h2 { font-weight: normal; color: #666; }
    #footer { background:#eee; overflow: auto; }
    #instructions { background:#f6f6f6; }
    #summary table { border:none; background:transparent; }
  </style>
</head>

<body>
<div id="summary">
{% block summary %}
{% endblock %}
</div>

<div id="instructions">
{% block instructions %}
{% endblock %}
</div>

<div id="footer">
  <p style="float: left;">Current Tenant:
      {% if request.tenant %}
      <a href="http://{{ request.tenant.domain_url }}:8000">{{ request.tenant.name }}</a>
      (<code>{{ request.tenant.schema_name }}</code>, <code>{{ request.tenant.domain_url }}</code>).

      Available Tenants:
      {% else %}
      None.
      {% endif %}
  {% for tenant in tenants_list %}
      <a href="http://{{ tenant.domain_url }}:8000">{{ tenant.name }}</a> &middot;
  {% endfor %}</p>
  <p style="float: right;">
    <a href="https://github.com/bernardopires/django-tenant-schemas">django-tenant-schemas</a> &middot; <a href="https://django-tenant-schemas.readthedocs.org/en/latest/">Documentation</a>
  </p>
</div>
</body></html>

templates/index_public.html
{% extends 'base.html' %}
{% block title %}Tenant Tutorial{% endblock %}

{% block summary %}
  <h1>Welcome to the Tenant Tutorial!</h1>
  <h2>This interactive tutorial will teach you how to use <a href="https://github.com/bernardopires/django-tenant-schemas">django-tenant-schemas</a>.</h2>
{% endblock %}

{% block instructions %}
{% if need_sync %}
    <h2>First Step: Sync your database</h2>
    <p>Your database is empty, so the first step is to sync it. We only want to sync the <code>SHARED_APPS</code>.
        For your convenience, here's the contents of <code>SHARED_APPS</code>:</p>
    <ul>
    {% for app in shared_apps %}
        <li>{{ app }}</li>
    {% endfor %}
    </ul><br>
    <p>Just run the command below on your shell to sync <code>SHARED_APPS</code>. Make sure your environment
    has <code>Django</code> and <code>django-tenant-schemas</code> available.</p>
    <pre>$ python manage.py sync_schemas --shared</pre>
    <p>When you're done refresh this page.</p>
{% elif no_public_tenant %}
    <h2>Second Step: Create a public tenant</h2>
    <h3>So how does django-tenant-schemas work?</h3>
    <p><code>django-tenant-schemas</code> uses the request's hostname to try to find a tenant.
        When a match is found,
        <a href="http://www.postgresql.org/docs/8.1/static/ddl-schemas.html">PostgreSQL's search path</a>
        is automatically set to be this tenant.</p>
    <br>
    <p>For this request, <code>django-tenant-schemas</code> couldn't find any tenant for the current address (<code>{{ hostname }}</code>).
        When no tenant is found, <code>django-tenant-schemas</code> normally returns a <code>404</code>, but since
        this is a tutorial and no tenant exists yet, we let it proceed.
    <h3>Recommended Tenant's URLs Structure</h3>
    <p>Let's assume you have your main website at <code>trendy-sass.com</code>. The recommended structure is
        to put your tenants at subdomains, like <code>tenant1.trendy-sass.com</code>,
        <code>tenant2.trendy-sass.com</code> and so forth.</p>
    <h3>Creating the public tenant</h3>
    <p><code>django-tenant-schemas</code> requires a tenant for all addresses you use, including your main website,
        which we will from now on refer to as the public tenant.</p>
    <br>
    <p>Our model is called <code>Customer</code> and looks like this (taken from <code>models.py</code>):</p>
    <pre>
class Client(TenantMixin):
    name = models.CharField(max_length=100)
    description = models.TextField(max_length=200)
    created_on = models.DateField(auto_now_add=True)</pre>
    <p>Let's create a tenant for our main website, located at <code>{{ hostname }}</code>. Open up a shell and enter the <code>django</code> shell:</p>
    <pre>$ ./manage.py shell</pre>
    <p>To create a tenant run the following commands:</p>
<pre>from customers.models import Client</pre>
<pre>
Client(domain_url='{{ hostname }}',
    schema_name='public',
    name='Trendy SaSS',
    description='Public Tenant').save()</pre>
    <p>Done! <code>django-tenant-schemas</code> will now be able to locate our public tenant and won't return 404. Refresh this page to see the next step.</p>
{% elif only_public_tenant %}
    <h2>Third Step: Create Tenants</h2>
    <p>We've already created the public tenant, now it's time to create some tenants for subdomains. I assume you're running this on your local machine,
        so the easiest way to simulate domains is to edit your <a href="http://en.wikipedia.org/wiki/Hosts_(file)"><code>hosts</code> file</a>.
        <a href="http://www.rackspace.com/knowledge_center/article/how-do-i-modify-my-hosts-file">Here are instructions for all platforms</a>.
        I'll assume you're on Linux.</p>
<pre>$ sudo nano /etc/hosts </pre>
    <p>Add the following lines:</p>
<pre>
127.0.0.1	tenant1.trendy-sass.com
127.0.0.1	tenant2.trendy-sass.com</pre>
    <p>We're basically tricking our computer to think both <code>tenant1.trendy-sass.com</code> and <code>tenant2.trendy-sass.com</code> point to <code>127.0.0.1</code>.
        Once you're done, try visiting <a href="http://tenant1.trendy-sass.com:8000">tenant1.trendy-sass.com</a>,
        you should get a django <code>404</code>. As we have previously mentioned, we don't have a tenant there yet, so a <code>404</code> will be thrown.<br></p>
    <br>
    <p>We can now add tenants using these URLs and our project will be able to find them and identify them as our tenants. Back to the django shell:</p>

<pre>$ ./manage.py shell</pre>
<pre>from customers.models import Client</pre>
<pre>
Client(domain_url='tenant1.trendy-sass.com',
    schema_name='tenant1',
    name='Tenant1 - Awesome',
    description='Our first real tenant, awesome!').save()</pre>
    <p>Saving a tenant that didn't exist before will create their schema and sync <code>TENANT_APPS</code> automatically. You should see
    the following lines as the result.</p>
<pre>=== Running syncdb for schema: tenant1
Creating tables ...
Creating table auth_permission
Creating table auth_group_permissions
Creating table auth_group
Creating table auth_user_groups
Creating table auth_user_user_permissions
Creating table auth_user
Creating table django_content_type
Installing custom SQL ...
Installing indexes ...
Installed 0 object(s) from 0 fixture(s)</pre>
    <p>This means your tenant was installed successfully. Now create the second tenant.</p>
<pre>
Client(domain_url='tenant2.trendy-sass.com',
    schema_name='tenant2',
    name='Tenant2 - Even Awesome-r',
    description='A second tenant, even more awesome!').save()</pre>

    <p>Now try visiting <a href="http://tenant1.trendy-sass.com:8000">tenant1.trendy-sass.com</a> and
        <a href="http://tenant2.trendy-sass.com:8000">tenant2.trendy-sass.com</a> or refresh this page.</p>
{% else %}
    <h2>Tutorial Complete!</h2>
    <p>Well done, you have completed the tutorial! Use the bottom menu to see your tenants.</p>
    <h3>Where to go from here</h3>
    <p>There are some interesting features that we did not cover.</p>
    <ul>
        <li><a href="https://django-tenant-schemas.readthedocs.org/en/latest/install.html#south-migrations">South Migrations</a>. This app supports <code>South</code> migrations.</li>
        <li><a href="https://django-tenant-schemas.readthedocs.org/en/latest/install.html#tenant-view-routing">Tenant View-Routing</a>. Serve different views for the same path. (this tutorial makes use of this feature)</li>
        <li><a href="https://django-tenant-schemas.readthedocs.org/en/latest/use.html#management-commands">Management Commands</a>. Run a command for a particular tenant.</li>
    </ul>
{% endif %}
{% endblock %}

templates/index_tenant.html
{% extends 'base.html' %}
{% block title %}{{ request.tenant.name }}{% endblock %}

{% block summary %}
  <h1>{{ request.tenant.name }}</h1>
  <h2>{{ request.tenant.description }}</h2>
{% endblock %}

{% block instructions %}
    <p>Each tenant is on a separate schema and contains different data. Take a look at the users list of this tenant.</p>
    <h3>Users List</h3>
{% if users %}
    <ul>
    {% for user in users %}
        <li>{{ user.first_name }} {{ user.last_name }}</li>
    {% endfor %}
    </ul>
{% else %}
    <p>You don't have any users!</p>
{% endif %}
    <h3>Generate Random Users</h3>
    <p>Click the button below to generate five random users.</p><br>
    <form action="" method="post">{% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Generate Users" />
    </form>
{% endblock %}